// js/core/state.js

export const state = {
    currentUser: null,
    isAdmin: false,
    isDataLoaded: false,
    isBattling: false,
    myDisplayName: "유저",
    myCards: [],
    money: 1000,
    potions: 3,
    atkPotions: 0,
    fusionScrolls: 0,
    upgItems: 0,
    expTickets: 0,
    winTickets: 0,
    capTickets: 0,
    userCapTickets: 0,
    rateUpTickets: 0,
    aiWins: 0,
    aiWinStreak: 0,
    exploreCount: 0,
    tourneyWins: 0,
    tournTickets: 3,
    skips: 0,
    claimedMails: {},
    serverMails: {},
    fusionCards: [null, null],
    aiAttackDeck: [null, null],
    pvpAttackDeck: [null, null, null],
    exploreCards: [null, null, null],
    defenseDeck: [null, null, null],
    plunderAttackDeck: [null, null, null],
    hcAttackDeck: [null, null, null],
    tnAttackDeck: [null],
    pvpTargetUser: null,
    currentDefender: null,
    selectionTarget: {mode: null, slotIdx: null},
    sellMode: false,
    selectedForSell: new Set(),
    tournData: null,
    tournParts: null,
    nextRunTime: null,
    pendingBattleResult: null
};
